android.useAndroidX=true
android.enableJetifier=false
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Force the Compose compiler version
android.suppressUnsupportedCompileSdk=35
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
kotlin.code.style=official

# Disable Kotlin version compatibility check for Compose
compose.kotlin.suppressKotlinVersionCompatibilityCheck=true 